package samebutdifferent.ecologics.registry;

import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.minecraft.block.*;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.util.registry.Registry;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.Material;
import net.minecraft.world.level.material.MaterialColor;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import samebutdifferent.ecologics.Ecologics;
import samebutdifferent.ecologics.block.*;
import samebutdifferent.ecologics.block.grower.WalnutTreeGrower;
import samebutdifferent.ecologics.block.properties.ModWoodType;

import java.util.function.Supplier;

public class ModBlocks {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(Ecologics.MOD_ID, Registry.BLOCK_KEY);

    public static final RegistrySupplier<PillarBlock> COCONUT_LOG = registerBlock("coconut_log", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.OAK_LOG)));
    public static final RegistrySupplier<PillarBlock> STRIPPED_COCONUT_LOG = registerBlock("stripped_coconut_log", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.STRIPPED_OAK_LOG)));
    public static final RegistrySupplier<PillarBlock> COCONUT_WOOD = registerBlock("coconut_wood", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.OAK_WOOD)));
    public static final RegistrySupplier<PillarBlock> STRIPPED_COCONUT_WOOD = registerBlock("stripped_coconut_wood", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.STRIPPED_OAK_WOOD)));
    public static final RegistrySupplier<CoconutLeavesBlock> COCONUT_LEAVES = registerBlock("coconut_leaves", () -> new CoconutLeavesBlock(AbstractBlock.Settings.copy(Blocks.OAK_LEAVES)));
    public static final RegistrySupplier<Block> COCONUT_PLANKS = registerBlock("coconut_planks", () -> new Block(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<SlabBlock> COCONUT_SLAB = registerBlock("coconut_slab", () -> new SlabBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<StairsBlock> COCONUT_STAIRS = registerBlock("coconut_stairs", () -> new StairsBlock(Blocks.OAK_PLANKS::defaultBlockState, AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<FenceBlock> COCONUT_FENCE = registerBlock("coconut_fence", () -> new FenceBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<FenceGateBlock> COCONUT_FENCE_GATE = registerBlock("coconut_fence_gate", () -> new FenceGateBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<DoorBlock> COCONUT_DOOR = registerBlock("coconut_door", () -> new DoorBlock(AbstractBlock.Settings.copy(Blocks.OAK_DOOR)));
    public static final RegistrySupplier<TrapdoorBlock> COCONUT_TRAPDOOR = registerBlock("coconut_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Settings.copy(Blocks.OAK_TRAPDOOR)));
    public static final RegistrySupplier<WoodenButtonBlock> COCONUT_BUTTON = registerBlock("coconut_button", () -> new WoodButtonBlock(AbstractBlock.Settings.copy(Blocks.OAK_BUTTON)));
    public static final RegistrySupplier<PressurePlateBlock> COCONUT_PRESSURE_PLATE = registerBlock("coconut_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Settings.copy(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistrySupplier<ModStandingSignBlock> COCONUT_SIGN = BLOCKS.register("coconut_sign", () -> new ModStandingSignBlock(AbstractBlock.Settings.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.COCONUT));
    public static final RegistrySupplier<ModWallSignBlock> COCONUT_WALL_SIGN = BLOCKS.register("coconut_wall_sign", () -> new ModWallSignBlock(AbstractBlock.Settings.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(COCONUT_SIGN.get()), ModWoodType.COCONUT));
    public static final RegistrySupplier<HangingCoconutBlock> HANGING_COCONUT = BLOCKS.register("hanging_coconut", HangingCoconutBlock::new);
    public static final RegistrySupplier<CoconutBlock> COCONUT = registerBlock("coconut", CoconutBlock::new);
    public static final RegistrySupplier<SaplingBlock> COCONUT_HUSK = registerBlock("coconut_husk", CoconutSaplingBlock::new);
    public static final RegistrySupplier<FlowerPotBlock> POTTED_COCONUT_HUSK = BLOCKS.register("potted_coconut_husk", () -> new FlowerPotBlock(ModBlocks.COCONUT_HUSK.get(), AbstractBlock.Settings.of(Material.DECORATION).instabreak().noOcclusion()));
    public static final RegistrySupplier<SeashellBlock> SEASHELL = registerBlock("seashell", SeashellBlock::new);
    public static final RegistrySupplier<SandcastleBlock> SANDCASTLE = BLOCKS.register("sandcastle", SandcastleBlock::new);
    public static final RegistrySupplier<Block> SEASHELL_BLOCK = registerBlock("seashell_block", () -> new Block(AbstractBlock.Settings.of(Material.STONE, MaterialColor.COLOR_BROWN).strength(1.5F, 6.0F).sound(SoundType.DEEPSLATE_TILES).requiresCorrectToolForDrops()));
    public static final RegistrySupplier<Block> SEASHELL_TILES = registerBlock("seashell_tiles", () -> new Block(AbstractBlock.Settings.copy(SEASHELL_BLOCK.get())));
    public static final RegistrySupplier<StairsBlock> SEASHELL_TILE_STAIRS = registerBlock("seashell_tile_stairs", () -> new StairBlock(() -> SEASHELL_BLOCK.get().defaultBlockState() ,AbstractBlock.Settings.copy(SEASHELL_BLOCK.get())));
    public static final RegistrySupplier<SlabBlock> SEASHELL_TILE_SLAB = registerBlock("seashell_tile_slab", () -> new SlabBlock(AbstractBlock.Settings.copy(SEASHELL_BLOCK.get())));
    public static final RegistrySupplier<WallBlock> SEASHELL_TILE_WALL = registerBlock("seashell_tile_wall", () -> new WallBlock(AbstractBlock.Settings.copy(SEASHELL_BLOCK.get())));
    public static final RegistrySupplier<PricklyPearBlock> PRICKLY_PEAR = BLOCKS.register("prickly_pear", PricklyPearBlock::new);
    public static final RegistrySupplier<PotBlock> POT = registerBlock("pot", () -> new PotBlock(AbstractBlock.Settings.of(Material.STONE, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(1.0F)));
    public static final RegistrySupplier<ThinIceBlock> THIN_ICE = registerBlock("thin_ice", ThinIceBlock::new);
    public static final RegistrySupplier<Block> ICE_BRICKS = registerBlock("ice_bricks", () -> new Block(AbstractBlock.Settings.of(Material.ICE).friction(0.98F).strength(0.5F).sound(SoundType.GLASS)));
    public static final RegistrySupplier<StairsBlock> ICE_BRICK_STAIRS = registerBlock("ice_brick_stairs", () -> new StairBlock(() -> ICE_BRICKS.get().defaultBlockState(), AbstractBlock.Settings.copy(ICE_BRICKS.get())));
    public static final RegistrySupplier<SlabBlock> ICE_BRICK_SLAB = registerBlock("ice_brick_slab", () -> new SlabBlock(AbstractBlock.Settings.copy(ICE_BRICKS.get())));
    public static final RegistrySupplier<WallBlock> ICE_BRICK_WALL = registerBlock("ice_brick_wall", () -> new WallBlock(AbstractBlock.Settings.copy(ICE_BRICKS.get())));
    public static final RegistrySupplier<Block> SNOW_BRICKS = registerBlock("snow_bricks", () -> new Block(AbstractBlock.Settings.of(Material.SNOW).strength(0.5F).sound(SoundType.SNOW)));
    public static final RegistrySupplier<StairsBlock> SNOW_BRICK_STAIRS = registerBlock("snow_brick_stairs", () -> new StairBlock(() -> SNOW_BRICKS.get().defaultBlockState(), AbstractBlock.Settings.copy(SNOW_BRICKS.get())));
    public static final RegistrySupplier<SlabBlock> SNOW_BRICK_SLAB = registerBlock("snow_brick_slab", () -> new SlabBlock(AbstractBlock.Settings.copy(SNOW_BRICKS.get())));
    public static final RegistrySupplier<WallBlock> SNOW_BRICK_WALL = registerBlock("snow_brick_wall", () -> new WallBlock(AbstractBlock.Settings.copy(SNOW_BRICKS.get())));
    public static final RegistrySupplier<PillarBlock> WALNUT_LOG = registerBlock("walnut_log", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.OAK_LOG)));
    public static final RegistrySupplier<PillarBlock> STRIPPED_WALNUT_LOG = registerBlock("stripped_walnut_log", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.STRIPPED_OAK_LOG)));
    public static final RegistrySupplier<PillarBlock> WALNUT_WOOD = registerBlock("walnut_wood", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.OAK_WOOD)));
    public static final RegistrySupplier<PillarBlock> STRIPPED_WALNUT_WOOD = registerBlock("stripped_walnut_wood", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.STRIPPED_OAK_WOOD)));
    public static final RegistrySupplier<LeavesBlock> WALNUT_LEAVES = registerBlock("walnut_leaves", () -> new LeavesBlock(AbstractBlock.Settings.copy(Blocks.OAK_LEAVES)));
    public static final RegistrySupplier<Block> WALNUT_PLANKS = registerBlock("walnut_planks", () -> new Block(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<SlabBlock> WALNUT_SLAB = registerBlock("walnut_slab", () -> new SlabBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<StairsBlock> WALNUT_STAIRS = registerBlock("walnut_stairs", () -> new StairBlock(Blocks.OAK_PLANKS::defaultBlockState, AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<FenceBlock> WALNUT_FENCE = registerBlock("walnut_fence", () -> new FenceBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<FenceGateBlock> WALNUT_FENCE_GATE = registerBlock("walnut_fence_gate", () -> new FenceGateBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<DoorBlock> WALNUT_DOOR = registerBlock("walnut_door", () -> new DoorBlock(AbstractBlock.Settings.copy(Blocks.OAK_DOOR)));
    public static final RegistrySupplier<TrapdoorBlock> WALNUT_TRAPDOOR = registerBlock("walnut_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Settings.copy(Blocks.OAK_TRAPDOOR)));
    public static final RegistrySupplier<WoodenButtonBlock> WALNUT_BUTTON = registerBlock("walnut_button", () -> new WoodButtonBlock(AbstractBlock.Settings.copy(Blocks.OAK_BUTTON)));
    public static final RegistrySupplier<PressurePlateBlock> WALNUT_PRESSURE_PLATE = registerBlock("walnut_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Settings.copy(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistrySupplier<ModStandingSignBlock> WALNUT_SIGN = BLOCKS.register("walnut_sign", () -> new ModStandingSignBlock(AbstractBlock.Settings.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.WALNUT));
    public static final RegistrySupplier<ModWallSignBlock> WALNUT_WALL_SIGN = BLOCKS.register("walnut_wall_sign", () -> new ModWallSignBlock(AbstractBlock.Settings.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(WALNUT_SIGN.get()), ModWoodType.WALNUT));
    public static final RegistrySupplier<SaplingBlock> WALNUT_SAPLING = registerBlock("walnut_sapling", () -> new SaplingBlock(new WalnutTreeGrower(), AbstractBlock.Settings.copy(Blocks.OAK_SAPLING)));
    public static final RegistrySupplier<FlowerPotBlock> POTTED_WALNUT_SAPLING = BLOCKS.register("potted_walnut_sapling", () -> new FlowerPotBlock(ModBlocks.WALNUT_SAPLING.get(), AbstractBlock.Settings.of(Material.DECORATION).instabreak().noOcclusion()));
    public static final RegistrySupplier<AzaleaLogBlock> AZALEA_LOG = registerBlock("azalea_log", AzaleaLogBlock::new);
    public static final RegistrySupplier<FloweringAzaleaLogBlock> FLOWERING_AZALEA_LOG = registerBlock("flowering_azalea_log", FloweringAzaleaLogBlock::new);
    public static final RegistrySupplier<PillarBlock> STRIPPED_AZALEA_LOG = registerBlock("stripped_azalea_log", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.STRIPPED_OAK_LOG)));
    public static final RegistrySupplier<PillarBlock> AZALEA_WOOD = registerBlock("azalea_wood", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.OAK_WOOD)));
    public static final RegistrySupplier<FloweringAzaleaLogBlock> FLOWERING_AZALEA_WOOD = registerBlock("flowering_azalea_wood", FloweringAzaleaLogBlock::new);
    public static final RegistrySupplier<PillarBlock> STRIPPED_AZALEA_WOOD = registerBlock("stripped_azalea_wood", () -> new PillarBlock(AbstractBlock.Settings.copy(Blocks.STRIPPED_OAK_WOOD)));
    public static final RegistrySupplier<Block> AZALEA_PLANKS = registerBlock("azalea_planks", () -> new Block(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<Block> FLOWERING_AZALEA_PLANKS = registerBlock("flowering_azalea_planks", () -> new Block(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<SlabBlock> AZALEA_SLAB = registerBlock("azalea_slab", () -> new SlabBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<SlabBlock> FLOWERING_AZALEA_SLAB = registerBlock("flowering_azalea_slab", () -> new SlabBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<StairsBlock> AZALEA_STAIRS = registerBlock("azalea_stairs", () -> new StairBlock(Blocks.OAK_PLANKS::defaultBlockState, AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<StairsBlock> FLOWERING_AZALEA_STAIRS = registerBlock("flowering_azalea_stairs", () -> new StairBlock(Blocks.OAK_PLANKS::defaultBlockState, AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<FenceBlock> AZALEA_FENCE = registerBlock("azalea_fence", () -> new FenceBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<FenceBlock> FLOWERING_AZALEA_FENCE = registerBlock("flowering_azalea_fence", () -> new FenceBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<FenceGateBlock> AZALEA_FENCE_GATE = registerBlock("azalea_fence_gate", () -> new FenceGateBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<FenceGateBlock> FLOWERING_AZALEA_FENCE_GATE = registerBlock("flowering_azalea_fence_gate", () -> new FenceGateBlock(AbstractBlock.Settings.copy(Blocks.OAK_PLANKS)));
    public static final RegistrySupplier<DoorBlock> AZALEA_DOOR = registerBlock("azalea_door", () -> new DoorBlock(AbstractBlock.Settings.copy(Blocks.OAK_DOOR)));
    public static final RegistrySupplier<DoorBlock> FLOWERING_AZALEA_DOOR = registerBlock("flowering_azalea_door", () -> new DoorBlock(AbstractBlock.Settings.copy(Blocks.OAK_DOOR)));
    public static final RegistrySupplier<TrapdoorBlock> AZALEA_TRAPDOOR = registerBlock("azalea_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Settings.copy(Blocks.OAK_TRAPDOOR)));
    public static final RegistrySupplier<TrapdoorBlock> FLOWERING_AZALEA_TRAPDOOR = registerBlock("flowering_azalea_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Settings.copy(Blocks.OAK_TRAPDOOR)));
    public static final RegistrySupplier<WoodenButtonBlock> AZALEA_BUTTON = registerBlock("azalea_button", () -> new WoodButtonBlock(AbstractBlock.Settings.copy(Blocks.OAK_BUTTON)));
    public static final RegistrySupplier<PressurePlateBlock> AZALEA_PRESSURE_PLATE = registerBlock("azalea_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Settings.copy(Blocks.OAK_PRESSURE_PLATE)));
    public static final RegistrySupplier<AzaleaFlowerBlock> AZALEA_FLOWER = registerBlock("azalea_flower", AzaleaFlowerBlock::new);
    public static final RegistrySupplier<SurfaceMossBlock> SURFACE_MOSS = registerBlock("surface_moss", SurfaceMossBlock::new);
    public static final RegistrySupplier<MossLayerBlock> MOSS_LAYER = BLOCKS.register("moss_layer", MossLayerBlock::new);
    public static final RegistrySupplier<FlowerPotBlock> POTTED_AZALEA_FLOWER = BLOCKS.register("potted_azalea_flower", () -> new FlowerPotBlock(ModBlocks.AZALEA_FLOWER.get(), AbstractBlock.Settings.of(Material.DECORATION).instabreak().noOcclusion()));
    public static final RegistrySupplier<ModStandingSignBlock> AZALEA_SIGN = BLOCKS.register("azalea_sign", () -> new ModStandingSignBlock(AbstractBlock.Settings.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.AZALEA));
    public static final RegistrySupplier<ModWallSignBlock> AZALEA_WALL_SIGN = BLOCKS.register("azalea_wall_sign", () -> new ModWallSignBlock(AbstractBlock.Settings.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(AZALEA_SIGN.get()), ModWoodType.AZALEA));
    public static final RegistrySupplier<ModStandingSignBlock> FLOWERING_AZALEA_SIGN = BLOCKS.register("flowering_azalea_sign", () -> new ModStandingSignBlock(AbstractBlock.Settings.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.FLOWERING_AZALEA));
    public static final RegistrySupplier<ModWallSignBlock> FLOWERING_AZALEA_WALL_SIGN = BLOCKS.register("flowering_azalea_wall_sign", () -> new ModWallSignBlock(AbstractBlock.Settings.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(FLOWERING_AZALEA_SIGN.get()), ModWoodType.FLOWERING_AZALEA));
    
    private static <T extends Block> RegistrySupplier<T> registerBlock(String name, Supplier<T> block) {
        RegistrySupplier<T> toReturn = ModBlocks.BLOCKS.register(name, block);
        ModItems.ITEMS.register(name, () -> new BlockItem(toReturn.get(), new Item.Settings().group(Ecologics.TAB)));
        return toReturn;
    }
}
